    - name: Upload APK (arm)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-armeabi.apk
        path: app/build/outputs/apk/oss/debug/*-oss-armeabi-v7a-debug.apk

    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-arm64.apk
        path: app/build/outputs/apk/oss/debug/*-oss-arm64-v8a-debug.apk

    - name: Upload APK (x86)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-x86.apk
        path: app/build/outputs/apk/oss/debug/*-oss-x86-debug.apk

    - name: Upload APK (x64)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-x64.apk
        path: app/build/outputs/apk/oss/debug/*-oss-x86_64-debug.apk

    - name: Upload APK (universal)
      uses: actions/upload-artifact@v3
      with:
        name: nightly-universal.apk
        path: app/build/outputs/apk/oss/debug/*-oss-universal-debug.apk
        retention-days: 14
