name: Android CI

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches-ignore:
      - 'dev'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    # https://github.com/actions/virtual-environments/issues/578
    - name: Fix missing NDK dependency
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
    - name: Build rclone
      run: ./gradlew buildNative -p rclone
    - name: Build app
      run: ./gradlew assembleOssDebug
    - name: Upload APK
      uses: actions/upload-artifact@v2-preview
      with:
        name: universal.apk
        path: app/build/outputs/apk/oss/debug/app-oss-universal-debug.apk
